### ISSUE TITLE
Update for new sim backend

### ISSUE THREAD

**Issue by jamie-cunningham** [act3-ace/run-time-assurance#6]
Update to use [`safe-autonomy-simulation`](https://github.com/act3-ace/safe-autonomy-simulation) as the new simulation backend

**Comment by keatincf** [comment]
Re-opening issue to resolve release issues.  1.16.2 was released when the version should have been 1.18.4.  Current plan is to revert the changes to main since 1.16.1 and then reapply the latest updates.  I think the issue was caused by the updates being a squashed merge rather than a regular merge and tags to the post 1.16.1 releases either broke or weren't in the commit history.
